name: ai summarize

on:
  workflow_run:
    workflows: ["Validate PR Title"]
    types:
      - completed

jobs:
  summarize:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.pull_requests[0].base.ref == 'development' &&
      github.event.workflow_run.pull_requests[0].head.ref != 'e2e' &&
      github.event.workflow_run.pull_requests[0].head.ref != 'main' &&
      github.event.workflow_run.pull_requests[0].head.ref != 'development'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Debug Info
        run: |
          echo "Triggered by workflow_run"
          echo "Base ref: ${{ github.event.workflow_run.pull_requests[0].base.ref }}"
          echo "Head ref: ${{ github.event.workflow_run.pull_requests[0].head.ref }}"

      - name: summarize script
        run: |
          echo "AI Summary"
