name: ai summarize

on:
  pull_request:
  push:
    branches:
      - development

jobs:
  summarize:
    if: "!contains(github.event.pull_request.title, '(sync-branches)')"
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: summarize script
        run: |
          echo "AI Summary"
