name: ai summarize

on:
  pull_request:

jobs:
  summarize:
    if: |
      github.base_ref == 'development' &&
      github.head_ref != 'e2e' &&
      github.head_ref != 'main' &&
      github.head_ref != 'development'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Debug Info
        run: |
          echo "event_name: ${{ github.event_name }}"
          echo "base_ref: ${{ github.base_ref }}"
          echo "head_ref: ${{ github.head_ref }}"

      - name: summarize script
        run: |
          echo "AI Summary"

