# .github/workflows/ai-summarize.yml

name: ai summarize

on:
  push:
    branches:
      - development

jobs:
  summarize:
    if: |
        github.event_name == 'pull_request' &&
        github.base_ref == 'development' &&
        github.head_ref != 'e2e' &&
        github.head_ref != 'main'
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: summarize script
        run: |
          echo "AI Summary"
